server:
  port: 8883
  servlet:
    context-path: /
management:
  server:
    address: 127.0.0.1
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file: /Volumes/DYZ-document/Program/X-CodeRunSpace/log/commentservice/comment-service.log
  level:
    com.netflix.discovery: error
spring:
  profiles:
    include: discover-eureka
  application:
    name: commentservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DMS_DB_HOST:127.0.0.1}:3306/commentdb?charset=utf8mb4&useSSL=false
    username: ${DMS_DB_USERNAME:root}
    password: ${DMS_DB_PASSWORD:658080}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update